### ISSUE TITLE
Определить место для хранения всех песен

### ISSUE THREAD

**Issue by KeyJoo** [RadugaCamp/xx-songs#1]
# Песни для сборника Радуге XX лет
- [ ] облако@mail.ru
- [ ] Google.DRIVE

**Comment by nanomen** [comment]
Я думаю можно залить вообще на гитхаб :) в папку static, как вам идея?

**Comment by nanomen** [comment]
В принципе уже сделал, так намного проще, да и всем доступно сразу :)
