### ISSUE TITLE
Тест другой версии шаблона + Vue + Webpack

### ISSUE THREAD

**Issue by KeyJoo** [RadugaCamp/xx-songs#14]
# cordova template framework7 vue webpack

До этого пробовал шаблон Fr7(react).
Тест был проведён в период 23:18 - 23:55 (2018-08-02 четверг), а теперь, для сравнения с Vue.js

- https://www.npmjs.com/package/cordova-template-framework7-vue-webpack

**Comment by KeyJoo** [comment]
cordova run android --device
(see youtube Timo Ernst)


`$ cordova create bibi ru.raduga.bibi CoolSongs --template cordova-template-framework7-vue-webpack`

`$ cd bibi`

`$ npm install`
`$ npm audit fix`

`$ cordova platform add android`
`$ cordova platform`

[x] checked

`$ cordova prepare android`

`$ cordova platform add ios browser`
`$ cordova run ios -- --lr`
`$ cordova run browser -- --lr` (Error > Process in memory used! Solution: `$ ps aux | grep :8081`)


open project in VSCode

`$ code .`

`$ npm install -g eslint`
`$ sudo npm install -g eslint` **sudo!**

```
➜  texts sudo npm install -g eslint
[sudo] password for keyjoo:
/usr/local/bin/eslint -> /usr/local/lib/node_modules/eslint/bin/eslint.js
+ eslint@5.2.0
added 145 packages from 152 contributors in 4.406s
```
Вариант принят рабочим.

**Comment by vovs03** [comment]
# OSX

`cordova platform`
`cordova run osx`  :memo:`# Run & building Osx.app`

**See Gitlab Repo** >> Issueses

**Comment by vovs03** [comment]
# iOS solution

Previously need remove old version `ios@4.5.5`

**list of platforms**
- `cordova platform`

**remove**
- `cordova platform remove ios@4.5.5`
- `[issues/647](https://github.com/apache/cordova-ios/issues/647)`
  - ❤️ `npm install cordova-ios@latest`


![Снимок экрана 2020-04-13 в 20 13 30](https://user-images.githubusercontent.com/21124057/79142957-04284a00-7dc5-11ea-9f23-2dce58ec59e5.jpg)

![Снимок экрана 2020-04-13 в 20 27 44](https://user-images.githubusercontent.com/21124057/79143111-4ea9c680-7dc5-11ea-9aff-fe187177e188.jpg)
