### ISSUE TITLE
Залить песни в облако

### ISSUE THREAD

**Issue by KeyJoo** [RadugaCamp/xx-songs#5]
Ведь есть же материал за последние 5 лет.
начать хотя бы с 2016 (на примере 1 года)

- ...
- [x] 2016 сборник
- ...

DL == 2018.06.17 (18 проверка)

**Comment by nanomen** [comment]
Залил все сборники в папку statics + все песни, что у меня были в подготовленном виде (txt формат и разметка одинаковая)
